version: '3.4'

services:
  sourcingdb:
      container_name: sourcingdb
      restart: always
      volumes:
          - ${WEBAPP_STORAGE_HOME}/site:/data/db
          #- ./data:/data/db
      ports:
          - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  esourcing.product:
        container_name: esourcingproduct
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
        depends_on:
            - sourcingdb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8000:80"

  esourcing.sourcing:
      container_name: esourcingsourcing
      environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
          - "EventBus:HostName=rabbitmq"
      depends_on:
          - sourcingdb
          - rabbitmq
      volumes:
          - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
          - ${HOME}/.aspnet/https:/root/.aspnet/https/
      ports:
          - "8001:80"

